const FRIEND_ACTION_FULFILLED = "user/FRIEND_ACTION_FULFILLED";
const USER_POSITION_FULFILLED = "user/USER_POSITION_FULFILLED";
const USER_PROFILE_UPDATE_FULFILLED = "user/USER_PROFILE_UPDATE_FULFILLED";
const USER_FRIENDS_POSITION_FULFILLED = "user/USER_FRIENDS_POSITION_FULFILLED";
const FRIENDS_DATA_FULFILLED = "user/FRIENDS_DATA_FULFILLED";

export {
    FRIEND_ACTION_FULFILLED,
    USER_POSITION_FULFILLED,
    USER_PROFILE_UPDATE_FULFILLED,
    USER_FRIENDS_POSITION_FULFILLED,
    FRIENDS_DATA_FULFILLED,
};
