const POST_USER_MEETING_FULFILLED = "user/POST_USER_MEETING_FULFILLED";
const GET_USER_MEETING_FULFILLED = "user/GET_USER_MEETING_FULFILLED";
const DELETE_USER_MEETING_FULFILLED = "user/DELETE_USER_MEETING_FULFILLED";
const USER_FRIENDS_MEETINGS_FULFILLED = "user/USER_FRIENDS_MEETINGS_FULFILLED";
const SET_MEETING_ATTENDANCE_FULFILLED = "user/SET_MEETING_ATTENDANCE_FULFILLED";
const POST_USER_MEETING_REJECTED = "user/POST_USER_MEETING_REJECTED";
const GET_USER_MEETING_REJECTED = "user/GET_USER_MEETING_REJECTED";

export {
    POST_USER_MEETING_FULFILLED,
    GET_USER_MEETING_FULFILLED,
    DELETE_USER_MEETING_FULFILLED,
    USER_FRIENDS_MEETINGS_FULFILLED,
    SET_MEETING_ATTENDANCE_FULFILLED,
    POST_USER_MEETING_REJECTED,
    GET_USER_MEETING_REJECTED,
};
