const USER_LOGIN_PENDING = "user/USER_LOGIN_PENDING";
const USER_LOGIN_REJECTED = "user/USER_LOGIN_REJECTED";
const USER_LOGIN_FULFILLED = "user/USER_LOGIN_FULFILLED";
const USER_REGISTER_FULFILLED = "user/USER_REGISTER_FULFILLED";
const USER_LOGOUT = "user/USER_LOGOUT";
const FRIEND_ACTION_FULFILLED = "user/FRIEND_ACTION_FULFILLED";
const USER_POSITION_FULFILLED = "user/USER_POSITION_FULFILLED";
const USER_FRIENDS_POSITION_FULFILLED = "user/USER_FRIENDS_POSITION_FULFILLED";
const USER_PROFILE_UPDATE_FULFILLED = "user/USER_PROFILE_UPDATE_FULFILLED";

export {
    USER_LOGIN_PENDING,
    USER_LOGIN_FULFILLED,
    USER_LOGIN_REJECTED,
    USER_REGISTER_FULFILLED,
    USER_LOGOUT,
    FRIEND_ACTION_FULFILLED,
    USER_POSITION_FULFILLED,
    USER_FRIENDS_POSITION_FULFILLED,
    USER_PROFILE_UPDATE_FULFILLED,
};
